/**
 * Copyright (c) 2025 XBXyftx
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


export * from './src/main/ets/components/NewsComponents/NewsSwiper'
export * from './src/main/ets/managers/UserConfigManager'
export * from './src/main/ets/managers/ColorModManager'
export * from './src/main/ets/components/ConfigeComponents/ColorModChoseButton'
export * from './src/main/ets/components/ConfigeComponents/FontSizeAdjustButton'
export * from './src/main/ets/managers/NewsManager'
export * from './src/main/ets/components/NewsComponents/NewsList'
export * from './src/main/ets/components/NewsComponents/NewsArticle'