# 
# Copyright (c) 2025 XBXyftx
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nowinopen harmony-server:latest
    container_name: openharmony-api
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - DATABASE_URL=sqlite:///./data/openharmony_news.db
      - LOG_LEVEL=INFO
      - ENABLE_SCHEDULER=true
      - TZ=Asia/Shanghai
    volumes:
      - app_logs:/app/logs
      - app_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - openharmony_net

  # PostgreSQL数据库服务（推荐生产环境使用）
  postgres:
    image: postgres:15-alpine
    container_name: openharmony-db
    environment:
      POSTGRES_DB: openharmony_news
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-openharmony2025}
      TZ: Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - openharmony_net

  # Redis缓存服务（可选，用于更高性能的缓存）
  redis:
    image: redis:7-alpine
    container_name: openharmony-redis
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis2025}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - openharmony_net

  # Nginx反向代理（生产环境推荐）
  nginx:
    image: nginx:alpine
    container_name: openharmony-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - openharmony_net

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  app_logs:
    driver: local
  app_data:
    driver: local
  nginx_logs:
    driver: local

networks:
  openharmony_net:
    driver: bridge 